version: 2
jobs:
  build:
    machine: # for docker --privileged
      image: circleci/classic:latest
    working_directory: ~/workdir
    steps:
      - checkout
      - run: 
          name: Install deps & check project
          command: sh .circleci/circleci.sh
      - store_artifacts:
          path: ~/workdir/keep
